config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about', as: :about 

  resources :classifieds

end

app/models/classified.rb
class Classified < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  def post
    #@classifieds = Classified.all
  end

  def index
    @classifieds = Classified.all
  end

  def new
    @classified = Classified.new
  end

  def show
    @classified = Classified.find(params[:id])
  end 

  def create
    @classified = Classified.new(classified_params)
  
    if @classified.save
      redirect_to classifieds_path
    else
      render :new
    end
  end

  def edit
    @classified = Classified.find(params[:id])
  end 

  def update
  @classified = Classified.find(params[:id])
  
  if @classified.update(classified_params)
    redirect_to classifieds_path
  else
    render :edit
  end
end  

  def destroy
    @classified = Classified.find(params[:id])
    @classified.destroy
    redirect_to classifieds_path
  end  

   private

  def classified_params
    params.require(:classified).permit(:title, :author, :body)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/classifieds/edit.html.erb
<h1> Edit Add </h1>
<%= form_for @classified do |f| %>
  <%= f.label :title %>: 
  <%= f.text_field :title %>

  <%= f.label :author %> 
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/classifieds/index.html.erb
<h1> Classified Adds </h1>
<p><%= link_to 'New Add', new_classified_path %></p>
<% @classifieds.each do |add| %>
  <h2><%= add.title %></h2>
  <h3><%= add.author %></h3>
  <p><%= add.body %></p>
  <%= link_to 'Show Add', classified_path(add) %>
  <%= link_to 'Edit Add', edit_classified_path(add) %>
  <%= link_to 'Destroy post', add, method: :delete %>
<% end %>

app/views/classifieds/new.html.erb
<h1> New Post </h1>
<%= form_for @classified do |f| %>
  <%= f.label :title %>: 
  <%= f.text_field :title %>

  <%= f.label :author %> 
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/classifieds/post.html.erb
<h1>Classifieds#post</h1>
<p>Find me in app/views/classifieds/post.html.erb</p>

app/views/classifieds/show.html.erb
<h1> Add </h1>
<h2><%= @classified.title %></h2>
<h3><%= @classified.author %></h2>
<p><%= @classified.body %></p>
<%= link_to 'Back', classifieds_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %> |
<%= link_to 'About', about_path %> |
<%= link_to 'Posts', classifieds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classifieds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>